#!/bin/bash -l

set -e

grep -q "consul\s\+members" /root/.bash_history || fail-message "You haven't checked the status of the Consul server yet."

consul_members=$(consul members | grep alive | wc -l)
if [ "$consul_members" -lt "3" ]; then
    fail-message "The command 'consul members' did not show 2 alive nodes. Something went wrong"
fi

grep -q "nomad\s\+server\s\+members" /root/.bash_history || fail-message "You haven't checked the status of the Nomad server yet."

nomad_servers=$(nomad server members | grep alive | wc -l)
if [ "$nomad_servers" -lt "1" ]; then
    fail-message "The command 'nomad server members' did not show an alive server. Something went wrong."
fi

grep -q "nomad\s\+node\s\+status" /root/.bash_history || fail-message "You haven't checked the status of the Nomad client node yet."

nomad_clients=$(nomad node status | grep ready | wc -l)
if [ "$nomad_clients" -lt "2" ]; then
    fail-message "The command 'nomad node status' did not show 1 ready client. Something went wrong"
fi

exit 0